#!/bin/bash

# Script to create a new user and to
# email the password to the new user.
# Uses the gen-passwd script.

# Author: Peter Jansson

usage()
{
	echo "Need three arguments:"
	echo "    1: Username: Unique username of the new user."
	echo "    2: Full name: The full name of the new user, should probably be quoted."
	echo "    3: Email: The email address of the new user."
}

if [ "$#" -ne 3 ]
then
	usage
else
	adduser $1 -c "$2 <$3>" \
		&& gen-passwd $1 $3
fi

